### PR TITLE
Used QueryBuilders.queryStringQuery instead of simpleQueryStringQuery…

### PR DESCRIPTION
**Pull request by shendepu**
… which is consistent with get search hits to get total count

### CODE REVIEW

**Comment by shendepu** [comment]
When use a complex query string like `(fromDate:[* TO 1486560165933] AND (thruDate:[1486560165933 TO *] OR (NOT _exists_:thruDate)))`, total count return 0 if using simpleStringQuery

**Comment by jonesde** [comment]
The simple query string is used intentionally, ie:

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html

As opposed to what you propose here which is:

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html

The reason for this is that these search strings are typed in by end users, who are now typically all that technical, and the simple one is easier to use. A few existing transitions and such in SimpleScreens used for drop-downs also use this syntax and may need to change if this was changed.

This could be an option on the server, ie a parameter that tells it to use the full query syntax instead of simple, but still default to simple. Changing the default like this is not a good idea as it would break things for current users and code, and in general would be more difficult for end-users.

**Comment by shendepu** [comment]
But it uses queryStringQuery to do result search, [below code](https://github.com/moqui/moqui-elasticsearch/blob/99a951bf90b5507121a512f0db8ebff5a950c82f/service/org/moqui/search/SearchServices.xml#L284-L287)
```
// get the search hits
SearchRequestBuilder srb = elasticSearchClient.prepareSearch().setIndices(indexName)
    .setQuery(QueryBuilders.queryStringQuery((String) queryString)).setFrom(fromOffset).setSize(sizeLimit)
    .setFetchSource(true)
```
while get total count it uses simpleQueryStringQuery, [below code](https://github.com/moqui/moqui-elasticsearch/blob/99a951bf90b5507121a512f0db8ebff5a950c82f/service/org/moqui/search/SearchServices.xml#L314-L316)
```
// get the total search count
SearchRequestBuilder countSrb = elasticSearchClient.prepareSearch().setIndices(indexName)
    .setQuery(QueryBuilders.simpleQueryStringQuery((String) queryString)).setSize(0)
```

Despite of difference of simple query string and query string, it seems it should use one in two query consistently.

**Comment by jonesde** [comment]
I looked at the syntax again, and this is something that has changed since the original search service was written a long time ago. The non-simple query string, the one you are proposing, seems closest to the standard Lucene query strings that everything is based on, so yes that is the one we want to use. I applied your patch to change the count query to match the main query. Thank you for looking into this and submitting the pull request.

**Pull request merged**
