### PR TITLE
Data document field mappings

### PR DESCRIPTION
**Pull request by shendepu**
This way seems better than PR #6, and index settings and other field mappings can be configured.

### CODE REVIEW

**Comment by shendepu** [comment]
@jonesde how do you think about this PR?

**Comment by jonesde** [comment]
I don't know yet, haven't had time to review it.

**Comment by jonesde** [comment]
Is there anything specific you are trying to do with this?

We talked elsewhere about the text vs keyword issue, and I think that is something that will be really useful to support (ie for text type fields and optional keyword sub-field for sorting, etc). That would ideally be handled by both the mapping generated and the search service so the keyword sub-field is used for sorting if it is enabled.

I mentioned before I wanted to avoid getting into trying to provide configuration for all possible options in ElasticSearch, and that is more or less what this does. One thing to keep in mind is that right now everything is pretty agnostic to the underlying search tool, ie something like Apache Solr could be plugged in instead of ElasticSearch (not that I personally have any plans to do this sort of thing). Still, it's something I like to keep in mind when designing framework features. XML Screens are a pretty good example of where you can define screens that work in multiple render modes because most of the elements and attributes can be applied across various (ie html, text, csv, xsl-fo, etc).

For the text/keyword thing it could be enabled with a simple flag (text-indicator) field that both the mapping code and search service look at. The field might be called something like 'sortable' or some other similarly generic name.

For other things we'd need something else if we want to support them generically. I'd like to step back and discuss that more if we could... what other scenarios (and related settings) are most important for what you are doing?

For really generic ElasticSearch meta-data (mappings) like this the same thing applies as to the database... it doesn't make sense to make all options for different databases available, the meta-data (table/etc definitions) can be changed directly in the database. For ElasticSearch mappings can be set directly with ElasticSearch.

**Comment by shendepu** [comment]
Besides of keyword, there is one important piece I think should be a common case that field need to be customized with a custom analyzer. There are two typical cases:

- text is non-English, e.g. Chinese character requires non-standard tokenizer, 
- another is the content is in html, so a `html_strip` character filter need to apply. 

I agree with you that setting all elasticsearch mappings is not a good generic way for framework. So adding generic configuration on `DataDocument` then implement them for different underlying full text search solution, other specific settings should be done in other ways. 

The above two cases are important to me, configure it in elasticsearch separately is kind of verbose and redundant, and might need to do it for every `DataDocument`.  

Do you think configuring a custom analyzer is a generic case? 

if so, we might just need to add two additional fields on `DataDocumentField`: `sortable` and `analyzer`. And customer analyzer should be pre-configured by underlying full-text search service, like elasticsearch settings.

**Pull request closed without merging**
