### PR TITLE
Define server_ip as text rather than IP address

### PR DESCRIPTION
**Pull request by jenshp**
This pull request contains a work-around to a limitation when using moqui in a proxied environment (e.g. using an application server behind a web server).
Depending on the implementation, javax.servlet.ServletRequest.getLocalAddr() does not always return a string containing an IP address because that information might not be available to the servlet container. The returned value could be the serverName, a null string or an empty string.
As a result, when elasticsearch tries to parse the string assuming it contains an IP address, it generates an exception. Defining the server_ip field as text rather than IP address avoids this problem.

### CODE REVIEW

**Comment by jonesde** [comment]
Have you run into actual cases where getLocalAddr() returns something other than an IP address (v4 or v6)? I googled this and found some references to bugs in certain servlet containers and proxies where this happens, even though the spec says it returns only an IP address.

If we want a host name (getServerName()) it should go in a separate field, IMO. You don't want to search or segment analytics expected one and getting the other. With a separate field it could also leave server_ip null if getLocalAddr() returns something other than an IP address.

Thoughts?

**Comment by jenshp** [comment]
I do have a setup where moqui is run on tomcat and proxied from the apache web server through mod_proxy using the ajp protocol. This mounted on a CentOS 7, so using apache 2.4.6 and it returns the hostname instead of a valid IP address, hence the later exception.
I understand that this issue is fixed upon apache 2.4.10 onwards as documented at https://bz.apache.org/bugzilla/show_bug.cgi?id=56661#c16, where the getLocalAddr() method should return the server IP address from the proxy through an additional variable.
This setting in particular has only one server, so it does not really matter to record which server the log entry came from.
If leaving getLocalAddr() null when it contains something that is not an IP address does not have negative consequences, it would be preferable to having the hostname.

**Comment by jonesde** [comment]
I'll change the field to keyword for now (not text as it is more like an identifier and there is no point tokenizing it for indexing). BTW, this is meant to be something to identify the server, not the gateway or the route it came in through or the host in the request URL (which goes in request_host).

See the change in commit #5f79120.

This may be the best long-term solution as well, but I'll wait for your thoughts on it before closing this pull request.

**Comment by jenshp** [comment]
I tested commit #5f79120 and it works fine.

**Pull request closed without merging**
